[pytest]
addopts = -v -s --alluredir=allure-results --clean-alluredir
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
timeout = 300
log_cli = true
log_cli_level = INFO